name = Disigner
description = A layout utilising the golden ratio (or divine proportion).
preview = preview.png
template = disigner-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/disigner/disigner.layout.css
stylesheets[all][] = css/layouts/divine/disiber.layout.no-query.css
